### ISSUE TITLE
CreateProcess failed with error 2: The system cannot find the file specified.

### ISSUE THREAD

**Issue by YonatanKra** [electron-userland/electron-webpack-quick-start#11]
I've forked and cloned the project, installed everything via yarn and then tried `yarn dev` and got the error:
`CreateProcess failed with error 2: The system cannot find the file specified.`
With the following call stack.
```
Error: Renderer WDS exited with code 0
    at ChildProcessManager.child.on.code (\node_modules\electron-webpack\src\dev\ChildProcessManager.ts:60:32)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
From previous event:
    at \node_modules\electron-webpack\src\dev\WebpackDevServerManager.ts:47:10
    at Generator.next (<anonymous>)
    at \node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:111:15)
From previous event:
    at startRenderer (\node_modules\electron-webpack\out\dev\WebpackDevServerManager.js:72:21)
    at \node_modules\electron-webpack\src\dev\dev-runner.ts:43:7
    at Generator.next (<anonymous>)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at DevRunner.start (\node_modules\electron-webpack\out\dev\dev-runner.js:133:11)
    at \node_modules\electron-webpack\src\dev\dev-runner.ts:140:19
    at Generator.next (<anonymous>)
From previous event:
    at main (\node_modules\electron-webpack\out\dev\dev-runner.js:42:22)
    at Object.<anonymous> (\node_modules\electron-webpack\src\dev\dev-runner.ts:143:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at runInDevMode (\node_modules\electron-webpack\src\cli.ts:36:2)
    at Object.__dirname.default.command.command.command.command.command.argv [as handler] (\node_modules\electron-webpack\src\cli.ts:16:16)
    at Object.runCommand (\node_modules\yargs\lib\command.js:228:22)
    at Object.parseArgs [as _parseArgs] (\node_modules\yargs\yargs.js:1013:30)
    at Object.get [as argv] (\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (\node_modules\electron-webpack\src\cli.ts:16:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```
Compile and build work just fine.  Can you tell why the dev isn't working?

**Comment by YonatanKra** [comment]
Update: I've upgraded node.js to version 8.9.1 (was version 7.0.0).  Did `npm install` (not `yarn`) and it is now working.

**Comment by jh3141** [comment]
Same problem with node 8.11.1.  `npm install` fails to work* and this error occurs with the yarn installed version.

* - it gives errors from installation of `uglifyjs-webpack-plugin` version 0.4.6 ... which is kind of unsurprising isn't working as that's an ancient version; yarn seems to install 1.2.0.

**Comment by jozsefm** [comment]
I face this problem too using node 8.11.1:
`┏ Renderer -------------------
CreateProcess failed with error 2: The system cannot find the file specified.
┗ ----------------------------
Error: Renderer WDS exited with code 0
    at ChildProcessManager.child.on.code (D:\myprojects\electron-realm\node_modules\electron-webpack\src\dev\ChildProcessManager.ts:62:32)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)`
In the specified path 
> node_modules\electron-webpack\src\dev\ChildProcessManager.ts:62:32

I can not see an src director nor anything coming after it. Do somebody have ideas how to fix it?

**Comment by peterb0yd** [comment]
I am also having this problem. Running on Windows 10.
