### ISSUE TITLE
Webpack 3.10.0 breaks build

### ISSUE THREAD

**Issue by LrsNate** [electron-userland/electron-webpack-quick-start#13]
Steps:
- clone the `electron-webpack-quick-start`
- Use `yarn upgrade-inteactive` to update webpack to v3.10.0
- Run `yarn compile`

Output:

```
/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276
        throw new Error(
              ^
Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
    at /Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:72:17
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:48:24)
    at SourceMapSource.node (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
    at /Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack-sources/lib/ConcatSource.js:59:50
    at Array.map (<anonymous>)
    at ConcatSource.node (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack-sources/lib/ConcatSource.js:58:63)
    at ConcatSource.proto.sourceAndMap (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
    at getTaskForFile (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack/lib/SourceMapDevToolPlugin.js:33:30)
    at chunk.files.forEach.file (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack/lib/SourceMapDevToolPlugin.js:91:21)
    at Array.forEach (<anonymous>)
    at /Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack/lib/SourceMapDevToolPlugin.js:89:18
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack/lib/SourceMapDevToolPlugin.js:88:12)
    at Compilation.applyPlugins1 (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/tapable/lib/Tapable.js:75:14)
    at self.applyPluginsAsync.err (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack/lib/Compilation.js:670:11)
    at next (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack/lib/ProgressPlugin.js:119:6)
    at next (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.compilation.plugin (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack/lib/BannerPlugin.js:67:5)
    at next (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.<anonymous> (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/babel-minify-webpack-plugin/dist/index.js:119:11)
    at Compilation.applyPluginsAsyncSeries (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack/lib/Compilation.js:666:10)
    at next (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin.callback (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/webpack/lib/ProgressPlugin.js:115:6)
    at Compilation.applyPluginsAsyncSeries (/Users/lafouaa/Personal/electron-webpack-quick-start/node_modules/tapable/lib/Tapable.js:206:13)
```

Seems to work fine when downgrading webpack back to 3.8.1.

The changelog for the [v3.10.0 release](https://github.com/webpack/webpack/releases/tag/v3.10.0) seems to mention changes to the sources map dev tool, but nothing that looks like it directly impacts source map generation. I'd assume this is an uncaught regression on their side (or the babel-minify-webpack-plugin breaks because of a breaking change from webpack).

**Comment by Donskelle** [comment]
Its related to https://github.com/webpack-contrib/babel-minify-webpack-plugin/issues/68#issuecomment-365574438

**Comment by develar** [comment]
I am going to get rid of babel-minify-webpack-plugin — and use uglifyjs-webpack-plugin instead (it is possible since end of 2017).

**Comment by develar** [comment]
Thanks a lot for discussion and links. Upcoming electron-webpack version now uses uglifyjs-webpack-plugin to minify code to fix this issue.
