### ISSUE TITLE
"original.line and original.column are not numbers" when using NPM

### ISSUE THREAD

**Issue by mitchhentges** [electron-userland/electron-webpack-quick-start#14]
**To reproduce:**
1. `git clone https://github.com/electron-userland/electron-webpack-quick-start`
2. `cd electron-webpack-quick-start`
3. `npm i`
4. `npm run compile`

**Expected Behaviour:**
This repository acts as an template (or a "quick start") of a working `electron-webpack` configuration. Therefore, this repository should work as-is without requiring any workarounds to cause it to build.

**Full error:**
```
/home/mitch/dev/electron-webpack-quick-start/node_modules/source-map/lib/source-map-generator.js:276
        throw new Error(
              ^
Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (/home/mitch/dev/electron-webpack-quick-start/node_modules/source-map/lib/source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (/home/mitch/dev/electron-webpack-quick-start/node_modules/source-map/lib/source-map-generator.js:110:12)
    at /home/mitch/dev/electron-webpack-quick-start/node_modules/source-map/lib/source-map-generator.js:72:17
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/home/mitch/dev/electron-webpack-quick-start/node_modules/source-map/lib/source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/home/mitch/dev/electron-webpack-quick-start/node_modules/source-map/lib/source-map-generator.js:48:24)
    at SourceMapSource.node (/home/mitch/dev/electron-webpack-quick-start/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
    at /home/mitch/dev/electron-webpack-quick-start/node_modules/webpack-sources/lib/ConcatSource.js:59:50
    at Array.map (<anonymous>)
    at ConcatSource.node (/home/mitch/dev/electron-webpack-quick-start/node_modules/webpack-sources/lib/ConcatSource.js:58:63)
    at ConcatSource.proto.sourceAndMap (/home/mitch/dev/electron-webpack-quick-start/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
    at getTaskForFile (/home/mitch/dev/electron-webpack-quick-start/node_modules/webpack/lib/SourceMapDevToolPlugin.js:33:30)
    at chunk.files.forEach.file (/home/mitch/dev/electron-webpack-quick-start/node_modules/webpack/lib/SourceMapDevToolPlugin.js:91:21)
    at Array.forEach (<anonymous>)
    at /home/mitch/dev/electron-webpack-quick-start/node_modules/webpack/lib/SourceMapDevToolPlugin.js:89:18
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (/home/mitch/dev/electron-webpack-quick-start/node_modules/webpack/lib/SourceMapDevToolPlugin.js:88:12)
    at Compilation.applyPlugins1 (/home/mitch/dev/electron-webpack-quick-start/node_modules/tapable/lib/Tapable.js:75:14)
    at self.applyPluginsAsync.err (/home/mitch/dev/electron-webpack-quick-start/node_modules/webpack/lib/Compilation.js:670:11)
    at next (/home/mitch/dev/electron-webpack-quick-start/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/home/mitch/dev/electron-webpack-quick-start/node_modules/webpack/lib/ProgressPlugin.js:119:6)
    at next (/home/mitch/dev/electron-webpack-quick-start/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.compilation.plugin (/home/mitch/dev/electron-webpack-quick-start/node_modules/webpack/lib/BannerPlugin.js:67:5)
    at next (/home/mitch/dev/electron-webpack-quick-start/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.<anonymous> (/home/mitch/dev/electron-webpack-quick-start/node_modules/babel-minify-webpack-plugin/dist/index.js:119:11)
    at Compilation.applyPluginsAsyncSeries (/home/mitch/dev/electron-webpack-quick-start/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/home/mitch/dev/electron-webpack-quick-start/node_modules/webpack/lib/Compilation.js:666:10)
    at next (/home/mitch/dev/electron-webpack-quick-start/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin.callback (/home/mitch/dev/electron-webpack-quick-start/node_modules/webpack/lib/ProgressPlugin.js:115:6)
    at Compilation.applyPluginsAsyncSeries (/home/mitch/dev/electron-webpack-quick-start/node_modules/tapable/lib/Tapable.js:206:13)
```

OS: `Arch Linux`
Node version: `v8.6.0`
NPM version: `3.10.10`

-----

[Sounds like it might be related to mismatching of versions](https://github.com/electron-userland/electron-webpack/issues/58), and this repo is set up to use yarn lockfiles, but for my project I can't just switch to use `yarn`.

**Comment by Hougo13** [comment]
This issue seems to come from [webpack-source](https://github.com/webpack/webpack-sources/issues/28) and [source-map](https://github.com/mozilla/source-map/issues/304).

**Comment by alexdevero** [comment]
The same here using `yarn`:
```
$ yarn run compile
yarn run v1.4.0
$ electron-webpack
 51% [0] chunk asset optimization
E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:276
        throw new Error(
              ^
Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:110:12)
    at E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:72:17
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack-sources\node_modules\source-map\lib\source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:48:24)
    at SourceMapSource.node (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack-sources\lib\SourceMapSource.js:32:35)
    at E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack-sources\lib\ConcatSource.js:59:50
    at Array.map (<anonymous>)
    at ConcatSource.node (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack-sources\lib\ConcatSource.js:58:63)
    at ConcatSource.proto.sourceAndMap (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack-sources\lib\SourceAndMapMixin.js:30:18)
    at getTaskForFile (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack\lib\SourceMapDevToolPlugin.js:33:30)
    at chunk.files.forEach.file (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack\lib\SourceMapDevToolPlugin.js:91:21)
    at Array.forEach (<anonymous>)
    at E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack\lib\SourceMapDevToolPlugin.js:89:18
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack\lib\SourceMapDevToolPlugin.js:88:12)
    at Compilation.applyPlugins1 (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\tapable\lib\Tapable.js:75:14)
    at self.applyPluginsAsync.err (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack\lib\Compilation.js:670:11)
    at next (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.compilation.plugin (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack\lib\ProgressPlugin.js:119:6)
    at next (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\tapable\lib\Tapable.js:204:14)
    at Compilation.compilation.plugin (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack\lib\BannerPlugin.js:67:5)
    at next (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\tapable\lib\Tapable.js:204:14)
    at Compilation.<anonymous> (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\babel-minify-webpack-plugin\dist\index.js:119:11)
    at Compilation.applyPluginsAsyncSeries (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\tapable\lib\Tapable.js:206:13)
    at self.applyPluginsAsync.err (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack\lib\Compilation.js:666:10)
    at next (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.compilation.plugin.callback (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\webpack\lib\ProgressPlugin.js:115:6)
    at Compilation.applyPluginsAsyncSeries (E:\Devero-Laboratories\WEB\clones-and-forks\electron-webpack-quick-start\node_modules\tapable\lib\Tapable.js:206:13)
error An unexpected error occurred: "Command failed.\nExit code: 1\nCommand: C:\\WINDOWS\\system32\\cmd.exe\nArguments: /d /s /c electron-webpack\nDirectory: E:\\Devero-Laboratories\\WEB\\clones-and-forks\\electron-webpack-quick-start\nOutput:\n".
info If you think this is a bug, please open a bug report with the information provided in "E:\\Devero-Laboratories\\WEB\\clones-and-forks\\electron-webpack-quick-start\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Gum-Joe** [comment]
@alexdevero have a look at electron-userland/electron-webpack#83

**Comment by Gum-Joe** [comment]
This issues was mistake open - the above is the correct issue

**Comment by Gum-Joe** [comment]
Also, here, turns out using eval-source-map errors when running the production build

**Comment by Gaston-Fartek** [comment]
I am experiencing the same issue, with a clean `git clone` and then `yarn` + `yarn dist`. Was anyone able to get this working?

**Comment by Gum-Joe** [comment]
I can not tell you unfortunately how to make it work, but I can tell you that a workaround is to put `devtool: process.env.NODE_ENV === "development" ? "source-map" : "none";`

**Comment by Gaston-Fartek** [comment]
Thanks @Gum-Joe, that worked!

**Comment by the-darc** [comment]
Thanks @Gum-Joe, that worked too!

To help newbies in webpack like me. Follow more explanations about how to apply the Gum-Joe's workaround:

1. Add the solution line in your [webpack configuration](https://webpack.electron.build/modifying-webpack-configurations) file:
```
/* custom.additions.webpack.js */

module.exports = {
  devtool: process.env.NODE_ENV === "development" ? "source-map" : "none"
};

```

2. Add a reference for your webpack's config file in your [electron-webpack configuration](https://webpack.electron.build/configuration) (package.json):
```
{
  "name": "electron-webpack-quick-start",
  // ------- . . . ------- //
  "electronWebpack": {
    "main": {
      "webpackConfig": "custom.additions.webpack.js"
    },
    "renderer": {
      "webpackConfig": "custom.additions.webpack.js",
      "webpackDllConfig": "custom.additions.webpack.js"
    }
  }
}
```

**Comment by mitchhentges** [comment]
Hey guys, it's good that we're finding workarounds (my personal favourite is to lock `webpack-sources` to `1.0.1`,  since it's the recent versions that started causing the error - `npm install webpack-sources@1.0.1`, and put it in your `package.json`), but these workarounds are solutions to problems in the underlying tooling, not `electron-webpack-quick-start` particularly.

I've edited the issue definition to clarify that this ticket is specifically about having `electron-webpack-quick-start` work out-of-the-box without requiring workarounds or modification.
IMHO, workarounds and manual solutions should be suggested and discussed in the issues for the underlying tooling, such as [the `webpack-sources` ticket](https://github.com/webpack/webpack-sources/issues/28)

**Comment by mitchhentges** [comment]
Oop, also looks like I duplicated the #13 issue btw :)

**Comment by Gum-Joe** [comment]
@the-darc Happy to help!

**Comment by develar** [comment]
Duplicates #13 

Thanks a lot for discussion and links. Upcoming electron-webpack version now uses uglifyjs-webpack-plugin to minify code to fix this issue.
