### ISSUE TITLE
Error on Mac

### ISSUE THREAD

**Issue by cdekok** [electron-userland/electron-webpack-quick-start#26]
On Linux it seems to work fine but on Mac i get the following error on node v9.7.1

```➜  electron-webpack-quick-start git:(master) yarn dev
yarn dev v0.21.3
$ electron-webpack dev
{ Error: spawn /Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/.bin/webpack-dev-server ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
From previous event:
    at /Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/electron-webpack/src/dev/WebpackDevServerManager.ts:47:10
    at Generator.next (<anonymous>)
    at /Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:171:5)
From previous event:
    at startRenderer (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/electron-webpack/out/dev/WebpackDevServerManager.js:72:21)
    at /Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/electron-webpack/src/dev/dev-runner.ts:43:7
    at Generator.next (<anonymous>)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at DevRunner.start (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/electron-webpack/out/dev/dev-runner.js:133:11)
    at /Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/electron-webpack/src/dev/dev-runner.ts:140:19
    at Generator.next (<anonymous>)
From previous event:
    at main (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/electron-webpack/out/dev/dev-runner.js:42:22)
    at Object.<anonymous> (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/electron-webpack/src/dev/dev-runner.ts:143:1)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at runInDevMode (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/electron-webpack/src/cli.ts:36:2)
    at Object.default.command.command.command.command.command.argv [as handler] (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/electron-webpack/src/cli.ts:16:16)
    at Object.runCommand (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/yargs/yargs.js:1014:30)
    at Object.get [as argv] (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/electron-webpack/src/cli.ts:16:16)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/.bin/webpack-dev-server',
  path: '/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/.bin/webpack-dev-server',
  spawnargs:
   [ '--color',
     '--env.autoClean=false',
     '--config',
     '/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/electron-webpack/webpack.renderer.config.js' ] }
Renderer WDS exited with code -2
┏ Main -----------------------

  Hash: eb639e0b9979ebc4a273
  Version: webpack 3.11.0
  Time: 513ms
    Asset   Size  Chunks             Chunk Names
  main.js  40 kB       0  [emitted]  main
  [./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js] ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js 559 bytes {0} [built]
  [./src/main/index.js] ./src/main/index.js 1.46 kB {0} [built]
  [electron] external "electron" 42 bytes {0} [not cacheable]
  [electron-webpack/out/electron-main-hmr/HmrClient] external "electron-webpack/out/electron-main-hmr/HmrClient" 42 bytes {0} [not cacheable]
  [path] external "path" 42 bytes {0} [not cacheable]
  [source-map-support/source-map-support.js] external "source-map-support/source-map-support.js" 42 bytes {0} [not cacheable]
  [url] external "url" 42 bytes {0} [not cacheable]
     [0] multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./src/main/index.js 40 bytes {0} [built]

┗ ----------------------------
```

Manually adding `webpack-cli` and `webpack-dev-server` results in a different error 

```
  TypeError: Cannot read property 'compile' of undefined
      at addCompilerHooks (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/webpack-dev-server/lib/Server.js:71:16)
      at new Server (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/webpack-dev-server/lib/Server.js:81:5)
      at startDevServer (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/webpack-dev-server/bin/webpack-dev-server.js:398:14)
      at processOptions (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/webpack-dev-server/bin/webpack-dev-server.js:361:5)
      at runCallback (timers.js:763:18)
      at tryOnImmediate (timers.js:734:5)
      at processImmediate (timers.js:716:5)
  From previous event:
      at processOptions (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/webpack-dev-server/bin/webpack-dev-server.js:241:20)
      at Object.<anonymous> (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/webpack-dev-server/bin/webpack-dev-server.js:504:1)
      at Module._compile (module.js:662:30)
      at Object.Module._extensions..js (module.js:673:10)
      at Module.load (module.js:575:32)
      at tryModuleLoad (module.js:515:12)
      at Function.Module._load (module.js:507:3)
      at Function.Module.runMain (module.js:703:10)
      at startup (bootstrap_node.js:193:16)
      at bootstrap_node.js:660:3

┗ ----------------------------
Error: Renderer WDS exited with code 0
    at ChildProcessManager.child.on.code (/Users/chrisdekok/Projects/electron-webpack-quick-start/node_modules/electron-webpack/src/dev/ChildProcessManager.ts:60:32)
```

**Comment by cdekok** [comment]
Strangely upgrading yarn fixed this issue 🆙
