### ISSUE TITLE
Unable to yarn dev  a fresh clone

### ISSUE THREAD

**Issue by jfaquinojr** [electron-userland/electron-webpack-quick-start#3]
Fresh clone of electron-webpack. Should i be able to yarn dev this? I also get the same error on my existing app.

```bash
D:\projects\electron-webpack-quick-start>yarn
yarn install v0.24.5
[1/5] Resolving packages...
success Already up-to-date.
Done in 1.00s.

D:\projects\electron-webpack-quick-start>yarn dev
yarn dev v0.24.5
$ electron-webpack dev
┏ Renderer -------------------

CreateProcess failed with error 2: The system cannot find the file specified.

┗ ----------------------------
Error: Renderer WDS exited with code 0
at ChildProcessManager.child.on.code (D:\projects\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\ChildProce
ssManager.ts:60:32)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:194:7)
at maybeClose (internal/child_process.js:899:16)
at Socket. (internal/child_process.js:342:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:191:7)
at Pipe._handle.close [as _onclose] (net.js:511:12)
From previous event:
at D:\projects\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\WebpackDevServerManager.ts:47:10
at Generator.next ()
at D:\projects\electron-webpack-quick-start\node_modules\graceful-fs\polyfills.js:287:18
at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
at startRenderer (D:\projects\electron-webpack-quick-start\node_modules\electron-webpack\out\dev\WebpackDevServerManager.js:72:
21)
at D:\projects\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\dev-runner.ts:37:7
at Generator.next ()
From previous event:
at DevRunner.start (D:\projects\electron-webpack-quick-start\node_modules\electron-webpack\out\dev\dev-runner.js:122:11)
at D:\projects\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\dev-runner.ts:131:19
at Generator.next ()
From previous event:
at main (D:\projects\electron-webpack-quick-start\node_modules\electron-webpack\out\dev\dev-runner.js:42:22)
at Object. (D:\projects\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\dev-runner.ts:134:1)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at runInDevMode (D:\projects\electron-webpack-quick-start\node_modules\electron-webpack\src\cli.ts:36:2)
at Object.__dirname.default.command.command.command.command.command.argv [as handler] (D:\projects\electron-webpack-quick-start
\node_modules\electron-webpack\src\cli.ts:16:16)
at Object.runCommand (D:\projects\electron-webpack-quick-start\node_modules\yargs\lib\command.js:226:22)
at Object.parseArgs [as _parseArgs] (D:\projects\electron-webpack-quick-start\node_modules\yargs\yargs.js:970:30)
at Object.get [as argv] (D:\projects\electron-webpack-quick-start\node_modules\yargs\yargs.js:912:21)
at Object. (D:\projects\electron-webpack-quick-start\node_modules\electron-webpack\src\cli.ts:16:16)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
┏ Main -----------------------

Hash: 5905c4b8b84576d437f9
Version: webpack 3.6.0
Time: 773ms
Asset Size Chunks Chunk Names
main.js 37.3 kB 0 [emitted] main
[./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js] ./node_modules/electron-webpack/out/electron-main-hmr/main-hm
r.js 559 bytes {0} [built]
[./src/main/index.js] ./src/main/index.js 1.22 kB {0} [built]
[electron] external "electron" 42 bytes {0} [not cacheable]
[electron-webpack/out/electron-main-hmr/HmrClient] external "electron-webpack/out/electron-main-hmr/HmrClient" 42 bytes {0} [not
cacheable]
[source-map-support/source-map-support.js] external "source-map-support/source-map-support.js" 42 bytes {0} [not cacheable]
[0] multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./src/main/index.js 40 bytes {0} [built]

┗ ----------------------------
```

**Comment by SimulatedGREG** [comment]
Please post some information about your development environment.

  * Node version:
  * NPM version:
  * yarn version: 
  * Operating System:

**Comment by jfaquinojr** [comment]
node: 
v7.10.0
npm: 
3.10.10
yarn: 
v0.24.5
OS:
Windows 10 Build 16296

**Comment by SimulatedGREG** [comment]
I would suggest that you try upgrading your `node` & `npm` to their latest versions. `yarn` officially doesn't support `node@^7`, so you might be running into some dependency issues.

**Comment by develar** [comment]
Cannot reproduce — yarn 1.1.0, node 8.5.0.
