### ISSUE TITLE
CreateProcess failed with error 193 (no message available)

### ISSUE THREAD

**Issue by aromot** [electron-userland/electron-webpack-quick-start#45]
Hello,

Win 7 (64 bits)
Yarn 1.12.1
Node 10.13.0

I've cloned the repo, deleted .git folder and installed dependencies running `yarn` (I did a `yarn cache clean` before).

When I launch `yarn dev`, I get:
`yarn run v1.12.1
$ electron-webpack dev
? Renderer -------------------

  CreateProcess failed with error 193 (no message available)

? ----------------------------
Error: Renderer WDS exited with code 0
    at ChildProcessManager.child.on.code (D:\informatique\programmation\js\electron\english\english-app-school2\node_modules\electron-webpack\src\dev\
ChildProcessManager.ts:62:32)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
From previous event:
    at D:\informatique\programmation\js\electron\english\english-app-school2\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at startRenderer (D:\informatique\programmation\js\electron\english\english-app-school2\node_modules\electron-webpack\out\dev\WebpackDevServerMana
ger.js:149:17)
    at D:\informatique\programmation\js\electron\english\english-app-school2\node_modules\electron-webpack\src\dev\dev-runner.ts:43:7
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at DevRunner.start (D:\informatique\programmation\js\electron\english\english-app-school2\node_modules\electron-webpack\src\dev\dev-runner.ts:32:1
4)
    at D:\informatique\programmation\js\electron\english\english-app-school2\node_modules\electron-webpack\src\dev\dev-runner.ts:142:19
    at Generator.next (<anonymous>)
From previous event:
    at main (D:\informatique\programmation\js\electron\english\english-app-school2\node_modules\electron-webpack\out\dev\dev-runner.js:132:18)
    at Object.<anonymous> (D:\informatique\programmation\js\electron\english\english-app-school2\node_modules\electron-webpack\src\dev\dev-runner.ts:1
45:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at runInDevMode (D:\informatique\programmation\js\electron\english\english-app-school2\node_modules\electron-webpack\src\cli.ts:35:3)
    at Object._yargs.default.command.command.command.command.command.argv [as handler] (D:\informatique\programmation\js\electron\english\english-app-
school2\node_modules\electron-webpack\src\cli.ts:13:71)
    at Object.runCommand (D:\informatique\programmation\js\electron\english\english-app-school2\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (D:\informatique\programmation\js\electron\english\english-app-school2\node_modules\yargs\yargs.js:1059:30)
    at Object.get [as argv] (D:\informatique\programmation\js\electron\english\english-app-school2\node_modules\yargs\yargs.js:1000:21)
    at Object.<anonymous> (D:\informatique\programmation\js\electron\english\english-app-school2\node_modules\electron-webpack\src\cli.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)`

I've searched but couldn't find any clue/hint/solution. I can't figure out where the problem comes from. Can anyone help?

**Comment by manolinjr81** [comment]
same problem here...

```console
$ yarn dev
yarn run v1.12.3
$ electron-webpack dev
┏ Renderer -------------------

  CreateProcess failed with error 193 (no message available)

┗ ----------------------------
Error: Renderer WDS exited with code 0
    at ChildProcessManager.child.on.code (D:\JS\Apps\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\ChildProcessManager.ts:62:32)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
From previous event:
    at D:\JS\Apps\electron-webpack-quick-start\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at startRenderer (D:\JS\Apps\electron-webpack-quick-start\node_modules\electron-webpack\out\dev\WebpackDevServerManager.js:149:17)
    at D:\JS\Apps\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\dev-runner.ts:43:7
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at DevRunner.start (D:\JS\Apps\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\dev-runner.ts:32:14)
    at D:\JS\Apps\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\dev-runner.ts:142:19
    at Generator.next (<anonymous>)
From previous event:
    at main (D:\JS\Apps\electron-webpack-quick-start\node_modules\electron-webpack\out\dev\dev-runner.js:132:18)
    at Object.<anonymous> (D:\JS\Apps\electron-webpack-quick-start\node_modules\electron-webpack\src\dev\dev-runner.ts:145:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at runInDevMode (D:\JS\Apps\electron-webpack-quick-start\node_modules\electron-webpack\src\cli.ts:35:3)
    at Object._yargs.default.command.command.command.command.command.argv [as handler] (D:\JS\Apps\electron-webpack-quick-start\node_modules\electron-webpack\src\cli.ts:13:71)
    at Object.runCommand (D:\JS\Apps\electron-webpack-quick-start\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (D:\JS\Apps\electron-webpack-quick-start\node_modules\yargs\yargs.js:1059:30)
    at Object.get [as argv] (D:\JS\Apps\electron-webpack-quick-start\node_modules\yargs\yargs.js:1000:21)
    at Object.<anonymous> (D:\JS\Apps\electron-webpack-quick-start\node_modules\electron-webpack\src\cli.ts:8:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
┏ Main -----------------------

  Hash: 3e18563d0105154cb698
  Version: webpack 4.24.0
  Time: 725ms
  Built at: 2018-11-09 15:45:06
    Asset      Size  Chunks             Chunk Names
  main.js  41.5 KiB    main  [emitted]  main
  Entrypoint main = main.js
  [0] multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./src/main/index.js 40 bytes {main} [built]
  [./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js] 582 bytes {main} [built]
  [./src/main/index.js] 1.42 KiB {main} [built]
  [electron] external "electron" 42 bytes {main} [built]
  [electron-webpack/out/electron-main-hmr/HmrClient] external "electron-webpack/out/electron-main-hmr/HmrClient" 42 bytes {main} [built]
  [path] external "path" 42 bytes {main} [built]
  [source-map-support/source-map-support.js] external "source-map-support/source-map-support.js" 42 bytes {main} [built]
  [url] external "url" 42 bytes {main} [built]

┗ ----------------------------
```
