### ISSUE TITLE
in China

### ISSUE THREAD

**Issue by zaoqi** [electron-userland/electron-webpack-quick-start#55]
```
$ yarn
yarn install v1.13.0
[1/5] Resolving packages...
[2/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/5] Linking dependencies...
[4/5] Building fresh packages...
[1/2] ⠂ electron
error /home/23494_sandbox/src/electron-webpack-quick-start/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/23494_sandbox/src/electron-webpack-quick-start/node_modules/electron
Output:
Downloading tmp-12121-0-electron-v4.0.1-linux-x64.zip
Error: read ECONNRESET
/home/23494_sandbox/src/electron-webpack-quick-start/node_modules/electron/install.js:49
  throw err
  ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:162:27)

$ yarn
yarn install v1.13.0
[1/5] Resolving packages...
[2/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/5] Linking dependencies...
[4/5] Building fresh packages...
[1/2] ⠈ electron
error /home/23494_sandbox/src/electron-webpack-quick-start/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/23494_sandbox/src/electron-webpack-quick-start/node_modules/electron
Output:
Downloading tmp-12240-0-electron-v4.0.1-linux-x64.zip
Error: read ECONNRESET
/home/23494_sandbox/src/electron-webpack-quick-start/node_modules/electron/install.js:49
  throw err
  ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:162:27)
```

**Comment by ikrong** [comment]
你可以使用淘宝 electron 镜像
```
yarn config set ELECTRON_MIRROR http://npm.taobao.org/mirrors/electron/
````
然后再执行 yarn
