### ISSUE TITLE
Development server does not work on windows

### ISSUE THREAD

**Issue by Manidos** [electron-userland/electron-webpack-quick-start#59]
Platform: Windows 10
Node: v8.12.0
Npm: 6.4.1

Hey! Freshly cloned repo gives an error when I run `npm run dev` through `powershell`. The same error when I run the command through shell provided by `git-scm` for windows.

```
  TypeError: Cannot read property 'bonjour' of undefined
      at createConfig (C:\Users\Predator\Desktop\dev\JS\electron-webpack-quick-start\node_modules\webpack-dev-server\lib\utils\createConfig.js:13:12)
      at processOptions (C:\Users\Predator\Desktop\dev\JS\electron-webpack-quick-start\node_modules\webpack-dev-server\lib\utils\processOptions.js:22:19)
      at runCallback (timers.js:810:20)
      at tryOnImmediate (timers.js:768:5)
      at processImmediate [as _immediateCallback] (timers.js:745:5)
  From previous event:
      at processOptions (C:\Users\Predator\Desktop\dev\JS\electron-webpack-quick-start\node_modules\webpack-dev-server\lib\utils\processOptions.js:9:12)
      at Object.<anonymous> (C:\Users\Predator\Desktop\dev\JS\electron-webpack-quick-start\node_modules\webpack-dev-server\bin\webpack-dev-server.js:172:1)
      at Module._compile (module.js:653:30)
      at Object.Module._extensions..js (module.js:664:10)
      at Module.load (module.js:566:32)
      at tryModuleLoad (module.js:506:12)
      at Function.Module._load (module.js:498:3)
      at Function.Module.runMain (module.js:694:10)
      at startup (bootstrap_node.js:204:16)
      at bootstrap_node.js:625:3
```

**Comment by Manidos** [comment]
I forgot to run `yarn` before running `npm run dev`
That's it.
