### ISSUE TITLE
yarn dist gets stuck in macos high sierra

### ISSUE THREAD

**Issue by djalmaaraujo** [electron-userland/electron-webpack-quick-start#6]
```bash
➜  electron-webpack-quick-start yarn dist
yarn run v1.1.0
$ yarn compile && electron-builder
[1] Hash: e9cc1cac9797f7917ed457bce8a7ecb870a59ad5
Version: webpack 3.6.0
Child
    Hash: e9cc1cac9797f7917ed4
    Time: 779ms
          Asset       Size  Chunks             Chunk Names
        main.js    1.14 kB       0  [emitted]  main
    main.js.map  748 bytes       0  [emitted]  main
       [0] multi ./src/main/index.js 28 bytes {0} [built]
       [1] ./src/main/index.js 1.41 kB {0} [built]
        + 1 hidden module
Child
    Hash: 57bce8a7ecb870a59ad5
    Time: 763ms
              Asset       Size  Chunks             Chunk Names
        renderer.js    3.31 kB       0  [emitted]  renderer
    renderer.js.map  853 bytes       0  [emitted]  renderer
         index.html  294 bytes          [emitted]
       [0] multi ./src/renderer/index.js 28 bytes {0} [built]
       [1] ./src/renderer/index.js 1.7 kB {0} [built]
        + 2 hidden modules
    Child html-webpack-plugin for "index.html":
         1 asset
           [0] ./node_modules/html-loader?minimize=false!/__virtual__/renderer-index.html 278 bytes {0} [built]
electron-builder 19.31.1
Using node_modules/electron-webpack/electron-builder.yml configuration file
⚠️  description is missed in the package.json (/Users/cooper/dev/me/electron-webpack-quick-start/package.json)
⚠️  author is missed in the package.json (/Users/cooper/dev/me/electron-webpack-quick-start/package.json)
No native production dependencies
Packaging for darwin x64 using electron 1.7.8 to dist/mac
⚠️  Application icon is not set, default Electron icon will be used
⚠️  App is not signed: cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing

All identities:
     0 identities found

  Valid identities only
     0 valid identities found
(node:94084) Warning: a promise was created in a handler at Users/cooper/dev/me/electron-webpack-quick-start/node_modules/electron-builder/src/macPackager.ts:89:26 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.map (/Users/cooper/dev/me/electron-webpack-quick-start/node_modules/bluebird/js/release/map.js:164:12)
Building macOS zip
Building DMG
⚠️  Application icon is not set, default Electron icon will be used
```

Running the latest version of this repo.. without changing anything on the code, I just tried ```yarn dist```.

**Comment by djalmaaraujo** [comment]
```js
"devDependencies": {
    "electron": "1.7.8",
    "electron-builder": "^19.34.1",
    "electron-webpack": "1.8.0",
    "webpack": "^3.6.0"
  }
```

**Comment by djalmaaraujo** [comment]
```bash
➜  electron-webpack-quick-start yarn dist
yarn run v1.1.0
$ DEBUG=electron-builder yarn compile && DEBUG=electron-builder electron-builder
[1] Hash: e9cc1cac9797f7917ed457bce8a7ecb870a59ad5
Version: webpack 3.6.0
Child
    Hash: e9cc1cac9797f7917ed4
    Time: 674ms
          Asset       Size  Chunks             Chunk Names
        main.js    1.14 kB       0  [emitted]  main
    main.js.map  748 bytes       0  [emitted]  main
       [0] multi ./src/main/index.js 28 bytes {0} [built]
       [1] ./src/main/index.js 1.41 kB {0} [built]
        + 1 hidden module
Child
    Hash: 57bce8a7ecb870a59ad5
    Time: 660ms
              Asset       Size  Chunks             Chunk Names
        renderer.js    3.31 kB       0  [emitted]  renderer
    renderer.js.map  853 bytes       0  [emitted]  renderer
         index.html  294 bytes          [emitted]
       [0] multi ./src/renderer/index.js 28 bytes {0} [built]
       [1] ./src/renderer/index.js 1.7 kB {0} [built]
        + 2 hidden modules
    Child html-webpack-plugin for "index.html":
         1 asset
           [0] ./node_modules/html-loader?minimize=false!/__virtual__/renderer-index.html 278 bytes {0} [built]
electron-builder 19.31.1
Using node_modules/electron-webpack/electron-builder.yml configuration file
  electron-builder Effective config:
  electron-builder extraMetadata:
  electron-builder   main: main.js
  electron-builder files:
  electron-builder   - from: .
  electron-builder     filter:
  electron-builder       - package.json
  electron-builder   - from: dist/main
  electron-builder   - from: dist/renderer
  electron-builder   - from: dist/renderer-dll
  electron-builder   - from: static
  electron-builder     to: static
  electron-builder extends: electron-webpack/electron-builder.yml
  electron-builder  +0ms
⚠️  description is missed in the package.json (/Users/cooper/dev/me/electron-webpack-quick-start/package.json)
⚠️  author is missed in the package.json (/Users/cooper/dev/me/electron-webpack-quick-start/package.json)
No native production dependencies
Packaging for darwin x64 using electron 1.7.8 to dist/mac
  electron-builder Spawning /Users/cooper/dev/me/electron-webpack-quick-start/node_modules/7zip-bin-mac/7za x -bd /Users/cooper/Library/Caches/electron/electron-v1.7.8-darwin-x64.zip -aoa -o/Users/cooper/dev/me/electron-webpack-quick-start/dist/mac +4s

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 48414779 bytes (47 MiB)

Extracting archive: /Users/cooper/Library/Caches/electron/electron-v1.7.8-darwin-x64.zip
--
Path = /Users/cooper/Library/Caches/electron/electron-v1.7.8-darwin-x64.zip
Type = zip
Physical Size = 48414779

Everything is Ok

Folders: 143
Files: 181
Size:       123416084
Compressed: 48414779
  electron-builder 7za (94273) exited with exit code 0 +2s
  electron-builder Directory /Users/cooper/dev/me/electron-webpack-quick-start/dist/renderer-dll doesn't exists, skip file copying +110ms
  electron-builder Directory /Users/cooper/dev/me/electron-webpack-quick-start/static doesn't exists, skip file copying +2ms
⚠️  Application icon is not set, default Electron icon will be used
  electron-builder Executing security find-identity -v +186ms
  electron-builder Executing security find-identity -v -p codesigning +10ms
  electron-builder      0 valid identities found
  electron-builder  +84ms
  electron-builder      0 valid identities found
  electron-builder  +11ms
  electron-builder Executing security find-identity +3ms
  electron-builder
  electron-builder Policy: X.509 Basic
  electron-builder   Matching identities
  electron-builder      0 identities found
  electron-builder
  electron-builder   Valid identities only
  electron-builder      0 valid identities found
  electron-builder  +97ms
⚠️  App is not signed: cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing

All identities:
     0 identities found

  Valid identities only
     0 valid identities found
(node:94270) Warning: a promise was created in a handler at Users/cooper/dev/me/electron-webpack-quick-start/node_modules/electron-builder/src/macPackager.ts:89:26 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.map (/Users/cooper/dev/me/electron-webpack-quick-start/node_modules/bluebird/js/release/map.js:164:12)
Building macOS zip
Building DMG
⚠️  Application icon is not set, default Electron icon will be used
  electron-builder Spawning /Users/cooper/dev/me/electron-webpack-quick-start/node_modules/7zip-bin-mac/7za a -bd -mx=9 -mtc=off -mm=Deflate -mcu /Users/cooper/dev/me/electron-webpack-quick-start/dist/electron-webpack-quick-start-0.0.0-mac.zip electron-webpack-quick-start.app +34ms
  electron-builder cwd: /Users/cooper/dev/me/electron-webpack-quick-start/dist/mac +2ms
  electron-builder macOS version: 10.13 +16ms
  electron-builder Spawning hdiutil create -srcfolder /Users/cooper/dev/me/electron-webpack-quick-start/dist/mac/electron-webpack-quick-start.app -volname electron-webpack-quick-start 0.0.0 -anyowners -nospotlight -format UDRW -fs HFS+ -fsargs -c c=64,a=16,e=16 /private/var/folders/v0/yqnl4_rs31368ggck6qr4fvr0000gn/T/temp-files-eRgQ23/0.dmg +2ms
................................................................................................
created: /private/var/folders/v0/yqnl4_rs31368ggck6qr4fvr0000gn/T/temp-files-eRgQ23/0.dmg
  electron-builder hdiutil (94278) exited with exit code 0 +10s
  electron-builder Spawning hdiutil resize -size 126673330 /private/var/folders/v0/yqnl4_rs31368ggck6qr4fvr0000gn/T/temp-files-eRgQ23/0.dmg +6ms
  electron-builder hdiutil (94305) exited with exit code 0 +67ms
  electron-builder Executing hdiutil attach -noverify -noautoopen -readwrite /private/var/folders/v0/yqnl4_rs31368ggck6qr4fvr0000gn/T/temp-files-eRgQ23/0.dmg +0ms
  electron-builder /dev/disk3          	GUID_partition_scheme
  electron-builder /dev/disk3s1        	Apple_HFS                      	/Volumes/electron-webpack-quick-start 0.0.0
  electron-builder  +672ms
  electron-builder Executing ln -s /Applications /Volumes/electron-webpack-quick-start 0.0.0/Applications +717ms
  electron-builder Executing /usr/bin/perl /private/var/folders/v0/yqnl4_rs31368ggck6qr4fvr0000gn/T/temp-files-eRgQ23/1-dmgProperties.pl +76ms
  electron-builder env: {
  electron-builder   "volumePath": "/Volumes/electron-webpack-quick-start 0.0.0",
  electron-builder   "appFileName": "electron-webpack-quick-start.app",
  electron-builder   "iconSize": 80,
  electron-builder   "iconTextSize": 12,
  electron-builder   "windowX": 400,
  electron-builder   "windowY": 100,
  electron-builder   "LC_ALL": "en_US.UTF-8",
  electron-builder   "VERSIONER_PERL_PREFER_32_BIT": "true",
  electron-builder   "backgroundFilename": "background.tiff"
  electron-builder } +10ms
  electron-builder cwd: /Users/cooper/dev/me/electron-webpack-quick-start/node_modules/dmg-builder/vendor +0ms
  electron-builder Executing hdiutil detach /dev/disk3 +239ms
  electron-builder "disk3" unmounted.
  electron-builder "disk3" ejected.
  electron-builder  +2s
  electron-builder Spawning hdiutil convert /private/var/folders/v0/yqnl4_rs31368ggck6qr4fvr0000gn/T/temp-files-eRgQ23/0.dmg -ov -format UDZO -o /Users/cooper/dev/me/electron-webpack-quick-start/dist/electron-webpack-quick-start-0.0.0.dmg -imagekey zlib-level=9 +2s
Preparing imaging engine…
Reading Protective Master Boot Record (MBR : 0)…
   (CRC32 $998C33CE: Protective Master Boot Record (MBR : 0))
Reading GPT Header (Primary GPT Header : 1)…
   (CRC32 $0BF4CA96: GPT Header (Primary GPT Header : 1))
Reading GPT Partition Data (Primary GPT Table : 2)…
   (CRC32 $D9CEC792: GPT Partition Data (Primary GPT Table : 2))
Reading  (Apple_Free : 3)…
   (CRC32 $00000000:  (Apple_Free : 3))
Reading disk image (Apple_HFS : 4)…
..................................................................................................................
   (CRC32 $639814EB: disk image (Apple_HFS : 4))
Reading  (Apple_Free : 5)…
..................................................................................................................
   (CRC32 $00000000:  (Apple_Free : 5))
Reading GPT Partition Data (Backup GPT Table : 6)…
..................................................................................................................
   (CRC32 $D9CEC792: GPT Partition Data (Backup GPT Table : 6))
Reading GPT Header (Backup GPT Header : 7)…
...................................................................................................................
   (CRC32 $1E4C6969: GPT Header (Backup GPT Header : 7))
Adding resources…
...................................................................................................................
Elapsed Time:  6.500s
File size: 48044550 bytes, Checksum: CRC32 $769AE970
Sectors processed: 247488, 242268 compressed
Speed: 18.2Mbytes/sec
Savings: 62.1%
created: /Users/cooper/dev/me/electron-webpack-quick-start/dist/electron-webpack-quick-start-0.0.0.dmg
  electron-builder hdiutil (94323) exited with exit code 0 +7s
```

with debug active it works.. any ideas why?

**Comment by develar** [comment]
Fixed in the latest electron-builder.
