### ISSUE TITLE
Try to "yarn dist", but get an error (windows)

### ISSUE THREAD

**Issue by nothinghappens** [electron-userland/electron-webpack-quick-start#62]
I git clone this repo and yarn, and then yarn dist immediately.
But I got this error...

Error: Exit code: ENOENT. spawn C:\Users\van20\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.4.0\rcedit-ia32.exe ENOENT
    at C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\builder-util\src\util.ts:126:16
    at exithandler (child_process.js:301:5)
    at ChildProcess.errorhandler (child_process.js:313:5)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.signAndEditResources (C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\winPackager.ts:260:158)
    at _bluebirdLst.default.map.file (C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\winPackager.ts:362:21)
    at go$readdir$cb (C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\graceful-fs\graceful-fs.js:162:14)
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\winPackager.ts:360:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\winPackager.ts:354:73)
    at C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\platformPackager.ts:250:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.doPack (C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
    at C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
    at C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\packager.ts:396:24)
    at C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\graceful-fs\graceful-fs.js:111:16
    at C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\packager.ts:335:133)
    at C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\electron-builder\src\builder.ts:228:10)
    at then (C:\wamp64\www\karaoke\electron-webpack-quick-start\node_modules\electron-builder\src\cli\cli.ts:49:19)
error

I use npm / yarn and rebuild many times... Still the same...

**Comment by nothinghappens** [comment]
Then I found it is caused by my anti-virus software.
If you are using McAfee, turn off its real-time scanning!
