### ISSUE TITLE
Cannot build starter app

### ISSUE THREAD

**Issue by sagism** [electron-userland/electron-webpack-quick-start#74]
I just installed the sample app with no changes.
Trying to build on mac I am getting an error with not enough details to troubleshoot:

$ yarn dist
yarn run v1.22.4
$ yarn compile && electron-builder
$ electron-webpack
Hash: 371a039ae728e55d9d11baef2c7d0e9feac2ca2c
Version: webpack 4.42.1
Child
    Hash: 371a039ae728e55d9d11
    Time: 2029ms
    Built at: 07/04/2020 10:23:02 AM
          Asset      Size  Chunks                   Chunk Names
        main.js  2.04 KiB       0  [emitted]        main
    main.js.map  2.51 KiB       0  [emitted] [dev]  main
    Entrypoint main = main.js main.js.map
    [0] external "electron" 42 bytes {0} [built]
    [1] external "path" 42 bytes {0} [built]
    [2] external "url" 42 bytes {0} [built]
    [3] multi ./src/main/index.js 28 bytes {0} [built]
    [4] ./src/main/index.js 1.48 KiB {0} [built]
Child
    Hash: baef2c7d0e9feac2ca2c
    Time: 2060ms
    Built at: 07/04/2020 10:23:02 AM
              Asset       Size  Chunks                   Chunk Names
         index.html  265 bytes          [emitted]        
        renderer.js   4.08 KiB       0  [emitted]        renderer
    renderer.js.map   2.46 KiB       0  [emitted] [dev]  renderer
    Entrypoint renderer = renderer.js renderer.js.map
    [0] multi ./src/renderer/index.js 28 bytes {0} [built]
    [1] ./src/renderer/index.js 1.72 KiB {0} [built]
    [3] external "electron" 42 bytes {0} [built]
        + 1 hidden module
    Child HtmlWebpackCompiler:
         1 asset
        Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
        [0] ./node_modules/html-loader/dist/cjs.js?minimize=false!./dist/.renderer-index-template.html 302 bytes {0} [built]
  • electron-builder  version=22.4.1 os=19.5.0
  • loaded parent configuration  file=/Users/sagi/projects/myproject/node_modules/electron-webpack/out/electron-builder.js
  • description is missed in the package.json  appPackageFile=/Users/sagi/projects/myproject/package.json
  • author is missed in the package.json  appPackageFile=/Users/sagi/projects/myproject/package.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=8.2.0 appOutDir=dist/mac
  • default Electron icon is used  reason=application icon is not set
  • file source doesn't exist  from=/Users/sagi/projects/myproject/static
  • signing         file=dist/mac/electron-webpack-quick-start.app identityName=Apple Development: Sagi Smolarski (NNNNN) identityHash=XXXXX provisioningProfile=none
  • building        target=macOS zip arch=x64 file=dist/electron-webpack-quick-start-0.0.0-mac.zip
  • building        target=DMG arch=x64 file=dist/electron-webpack-quick-start-0.0.0.dmg
  • building embedded block map  file=dist/electron-webpack-quick-start-0.0.0-mac.zip
  ⨯ hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                    Error: hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                        at ChildProcess.<anonymous> (/Users/sagi/projects/myproject/node_modules/builder-util/src/util.ts:239:14)
                                                                        at Object.onceWrapper (events.js:300:26)
                                                                        at ChildProcess.emit (events.js:210:5)
                                                                        at maybeClose (internal/child_process.js:1023:16)
                                                                        at Process.ChildProcess._handle.onexit (internal/child_process.js:281:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The file referenced (/Users/sagi/projects/myproject/node_modules/builder-util/src/util.ts) does not exist.

my package.json:

{
  "name": "electron-webpack-quick-start",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "dev": "electron-webpack dev",
    "compile": "electron-webpack",
    "dist": "yarn compile && electron-builder",
    "dist:dir": "yarn dist --dir -c.compression=store -c.mac.identity=null"
  },
  "dependencies": {
    "source-map-support": "^0.5.16"
  },
  "devDependencies": {
    "electron": "8.2.0",
    "electron-builder": "^22.4.1",
    "electron-webpack": "^2.8.2",
    "webpack": "~4.42.1"
  }
}

**Comment by sagism** [comment]
Solved this by doing a safe boot (shift-restart) so Sophos antivirus was disabled.
